import type { SiteSettings } from "@/lib/content/types";
import type { FieldDef } from "./fields";

/** Vietnes iestatījumu formas (tabula site_settings, katra sadaļa — viens JSON ieraksts). */

export type SettingsKey = keyof SiteSettings;

export const settingsSchemas: Record<SettingsKey, { title: string; description: string; fields: FieldDef[] }> = {
  home: {
    title: "Sākumlapa",
    description: "Sākumlapas virsraksts, teksti un bloki.",
    fields: [
      { name: "heroEyebrow", label: "Virsraksta etiķete", type: "text", wide: true },
      { name: "heroTitle", label: "Galvenais virsraksts", type: "text", wide: true },
      { name: "heroHighlight", label: "Izceltais vārds (tumšā uzlīmē)", type: "text" },
      { name: "heroAfter", label: "Virsraksta beigas", type: "text" },
      { name: "heroText", label: "Ievada teksts", type: "textarea", rows: 3, wide: true },
      { name: "heroTextMobile", label: "Ievada teksts telefonam (īsāks)", type: "textarea", rows: 2, wide: true },
      { name: "heroPoster", label: "Galvenes fotogrāfija", type: "image", wide: true },
      { name: "heroCtaPrimary", label: "Galvenās pogas teksts", type: "text" },
      { name: "heroCtaSecondary", label: "Otrās pogas teksts", type: "text" },
      { name: "servicesTitle", label: "Pakalpojumu bloka virsraksts", type: "text", wide: true },
      { name: "servicesText", label: "Pakalpojumu bloka teksts", type: "textarea", rows: 2, wide: true },
      { name: "whyTitle", label: "“Kāpēc mēs” virsraksts", type: "text", wide: true },
      { name: "whyText", label: "“Kāpēc mēs” teksts", type: "textarea", rows: 2, wide: true },
      { name: "why", label: "“Kāpēc mēs” punkti", type: "pairs", rows: 5, wide: true, help: "Katrā rindā: Virsraksts | apraksts (4 punkti)" },
      { name: "processTitle", label: "Darba procesa virsraksts", type: "text", wide: true },
      { name: "process", label: "Darba procesa soļi", type: "pairs", rows: 5, wide: true, help: "Katrā rindā: Solis | apraksts" },
      { name: "galleryTitle", label: "Fotolentes virsraksts", type: "text" },
      { name: "galleryText", label: "Fotolentes teksts", type: "text" },
      {
        name: "galleryImages",
        label: "Fotolentes attēli",
        type: "lines",
        rows: 8,
        wide: true,
        help: "Viena attēla adrese rindā. Adresi var nokopēt sadaļā “Foto”. Ja tukšs — izvēlas automātiski.",
      },
      { name: "xmasEnabled", label: "Rādīt Ziemassvētku reklāmu (sākumlapā un lapā “Uzņēmumiem”)", type: "checkbox" },
      { name: "xmasEyebrow", label: "Ziemassvētku bloka etiķete", type: "text", help: "Piem. Ziemassvētki 2026" },
      { name: "xmasTitle", label: "Ziemassvētku bloka virsraksts", type: "text" },
      { name: "xmasHighlight", label: "Izceltais vārds", type: "text" },
      { name: "xmasShort", label: "Ziemassvētku reklāma sākumlapā (īss teksts)", type: "textarea", rows: 2, wide: true },
      { name: "xmasText", label: "Ziemassvētku bloka teksts lapā “Uzņēmumiem”", type: "textarea", rows: 3, wide: true },
      { name: "xmasPoints", label: "Ziemassvētku bloka punkti", type: "lines", rows: 4, help: "Viens punkts rindā" },
      {
        name: "xmasPhotos",
        label: "Ziemassvētku bloka fotogrāfijas",
        type: "photos",
        rows: 3,
        wide: true,
        help: "Līdz 3 rindām: attēla adrese | paraksts",
      },
      { name: "ctaTitle", label: "Noslēguma aicinājuma virsraksts", type: "text" },
      { name: "ctaText", label: "Noslēguma aicinājuma teksts", type: "text" },
    ],
  },
  about: {
    title: "Par mums",
    description: "Lapas “Par mums” saturs. Komandu rediģē sadaļā “Komanda”.",
    fields: [
      { name: "title", label: "Virsraksts", type: "text", wide: true },
      { name: "intro", label: "Ievads", type: "textarea", rows: 3, wide: true },
      { name: "image", label: "Fotogrāfija", type: "image", wide: true },
      { name: "teamTitle", label: "Komandas bloka virsraksts", type: "text" },
      { name: "teamText", label: "Komandas bloka teksts", type: "text" },
    ],
  },
  business: {
    title: "Uzņēmumiem",
    description: "Sadaļas “Uzņēmumiem” galvene un teksti. Pakalpojumus (un to sezonas) rediģē sadaļā “Pakalpojumi”, Ziemassvētku bloku — sadaļā “Sākumlapa”.",
    fields: [
      { name: "heroTitle", label: "Virsraksts", type: "text", wide: true },
      { name: "heroHighlight", label: "Izceltais vārds virsrakstā", type: "text" },
      { name: "heroText", label: "Ievada teksts", type: "textarea", rows: 3, wide: true },
      { name: "winterText", label: "Ziemas piedāvājumu teksts", type: "textarea", rows: 2, wide: true },
      { name: "summerText", label: "Vasaras piedāvājumu teksts", type: "textarea", rows: 2, wide: true },
      { name: "allYearText", label: "“Visu gadu” teksts", type: "textarea", rows: 2, wide: true },
      { name: "showsTitle", label: "Izrāžu bloka virsraksts", type: "text" },
      { name: "showsText", label: "Izrāžu bloka teksts", type: "textarea", rows: 2, wide: true },
      { name: "photosTitle", label: "Fotogrāfiju bloka virsraksts", type: "text" },
    ],
  },
  shows: {
    title: "Izrādes",
    description: "Sadaļas “Izrādes” galvene, video un apraksts.",
    fields: [
      { name: "heroTitle", label: "Virsraksts", type: "text", wide: true },
      { name: "heroHighlight", label: "Izceltais vārds virsrakstā", type: "text" },
      { name: "heroText", label: "Ievada teksts", type: "textarea", rows: 3, wide: true },
      { name: "videosTitle", label: "Video bloka virsraksts", type: "text" },
      {
        name: "videos",
        label: "Video",
        type: "videos",
        rows: 6,
        wide: true,
        help: "Katrā rindā: Izrādes nosaukums | YouTube saite | vāciņa attēls (var atstāt tukšu) | ilgums | auditorija | apraksts. Piem.: Dāvanu prieks | https://youtu.be/… |  | 45 min | Visai ģimenei | Apraksts. Aprakstā ¶ = jauna rinda, ¶ ¶ = jauna rindkopa, \"- \" rindas sākumā = saraksta punkts, **teksts** = treknraksts.",
      },
      { name: "aboutTitle", label: "Apraksta virsraksts", type: "text" },
      { name: "body", label: "Apraksts", type: "textarea", rows: 8, wide: true, help: "Tukša rinda = jauna rindkopa" },
      { name: "highlights", label: "Galvenie punkti", type: "lines", rows: 4, help: "Viens punkts rindā" },
      { name: "suitableFor", label: "Kam piemērots", type: "lines", rows: 4, help: "Viens punkts rindā" },
    ],
  },
  venue: {
    title: "Telpu noma",
    description: "Sadaļas “Telpu noma” teksti, aprīkojums un telpu lietošanas noteikumi. Cenas maina izstrādātājs (src/lib/pricing.ts).",
    fields: [
      { name: "heroTitle", label: "Virsraksts", type: "text" },
      { name: "heroHighlight", label: "Izceltais vārds", type: "text" },
      { name: "heroAfter", label: "Virsraksta beigas", type: "text" },
      { name: "heroText", label: "Ievada teksts", type: "textarea", rows: 3, wide: true },
      { name: "aboutTitle", label: "Apraksta virsraksts", type: "text" },
      { name: "about", label: "Par telpām", type: "textarea", rows: 5, wide: true, help: "Tukša rinda = jauna rindkopa" },
      { name: "features", label: "Aprīkojums", type: "pairs", rows: 7, wide: true, help: "Katrā rindā: Nosaukums | apraksts" },
      { name: "included", label: "Cenā iekļauts", type: "lines", rows: 6, wide: true, help: "Katrā rindā viens punkts" },
      {
        name: "rules",
        label: "Telpu lietošanas noteikumi",
        type: "textarea",
        rows: 20,
        wide: true,
        help: "“## Virsraksts” sāk jaunu sadaļu, “- ” — saraksta punkts, **treknraksts**.",
      },
    ],
  },
  programs: {
    title: "Izklaides programmas",
    description: "Sadaļas “Izklaides programmas” galvene un teksti. Programmas rediģē sadaļā “Pakalpojumi”.",
    fields: [
      { name: "heroTitle", label: "Virsraksts", type: "text", wide: true },
      { name: "heroHighlight", label: "Izceltais vārds virsrakstā", type: "text" },
      { name: "heroText", label: "Ievada teksts", type: "textarea", rows: 3, wide: true },
    ],
  },
  contact: {
    title: "Kontakti",
    description: "Kontaktinformācija tiek rādīta kājenē, kontaktu lapā un Schema.org datos.",
    fields: [
      { name: "company", label: "Uzņēmuma nosaukums", type: "text" },
      { name: "phoneBusiness", label: "Telefons uzņēmumiem", type: "text" },
      { name: "phoneBusinessPerson", label: "Kontaktpersona uzņēmumiem", type: "text" },
      { name: "email", label: "E-pasts uzņēmumiem", type: "text" },
      { name: "phonePrivate", label: "Telefons privātpersonām", type: "text" },
      { name: "phonePrivatePerson", label: "Kontaktpersona privātpersonām", type: "text" },
      { name: "emailPrivate", label: "E-pasts privātpersonām", type: "text" },
      { name: "address", label: "Darbības adrese: iela, māja", type: "text" },
      { name: "city", label: "Pilsēta", type: "text" },
      { name: "postalCode", label: "Pasta indekss", type: "text" },
      { name: "hours", label: "Darba laiks", type: "text" },
      { name: "mapQuery", label: "Adrese Google kartei", type: "text", wide: true },
      { name: "facebook", label: "Facebook saite", type: "text", wide: true },
      { name: "instagram", label: "Instagram saite", type: "text", wide: true },
      { name: "tiktok", label: "TikTok saite", type: "text", wide: true },
      { name: "legalName", label: "Pilns juridiskais nosaukums", type: "text", wide: true },
      { name: "legalAddress", label: "Juridiskā adrese", type: "text", wide: true },
      { name: "regNr", label: "Reģistrācijas numurs", type: "text" },
      { name: "vatNr", label: "PVN numurs", type: "text" },
      { name: "bank", label: "Banka", type: "text" },
      { name: "iban", label: "Konta numurs (IBAN)", type: "text" },
    ],
  },
  seo: {
    title: "SEO iestatījumi",
    description: "Noklusējuma virsraksts un apraksts, ko izmanto sākumlapa un lapas bez sava apraksta.",
    fields: [
      { name: "siteName", label: "Vietnes nosaukums", type: "text" },
      { name: "defaultTitle", label: "Noklusējuma virsraksts", type: "text", wide: true },
      { name: "defaultDescription", label: "Noklusējuma apraksts", type: "textarea", rows: 3, wide: true },
      { name: "ogImage", label: "Noklusējuma attēls sociālajiem tīkliem", type: "image", wide: true },
    ],
  },
};
